### ISSUE TITLE
account freigabe automatisieren

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#133]
* for all signed up users from MPG domain, i.e. `.*@.*\.mpg.de$`

**Comment by kleinfe** [comment]
Bitte ein skript schreiben welches automatisch alle Nutzer mit einer email adresse die aud *mpg.de endet freischaltet.

**Comment by vmakarenko** [comment]
Solution: update seahub.base.accounts.RegistrationBackend.register#462 with regexp

**Comment by vmakarenko** [comment]
Update: use MPDL service for MPG domains handling as a source for the feature. Not all MPG-affiliated institutions are in *.mpg.de domain. TBD.

**Comment by vmakarenko** [comment]
Status: implemented on hand of http://colab.mpdl.mpg.de/mediawiki/Max_Planck_email_domains

**Comment by vmakarenko** [comment]
The list should be correctly updated, e.g. for the moment there is no MPCDF entry in it.

**Comment by kleinfe** [comment]
*.mpdl.mpg.de emails are not automatically activated

**Comment by hofmannc** [comment]
--> they are activated, but the message is wrong

**Comment by vmakarenko** [comment]
Fixed: activated user will be redirected to library view

**Comment by hofmannc** [comment]
Testserver: qa keeper
Browser: ff
Version: Seafile 6.1.3 ohne Datum 170720

Test result: ok. new mpdl.mpg.de user registered and correctly redirected.

**Comment by kleinfe** [comment]
![grafik](https://user-images.githubusercontent.com/1484773/28405403-58cbd71c-6d2d-11e7-8af0-14040e94d525.png)
Have to discuss how to solve this problem!

**Comment by vmakarenko** [comment]
Resolved. 
Solution: MPG users get an activation email and not automatically logged in. All other users can be activated only by admin.

**Comment by hofmannc** [comment]
Testserver: qa keeper
Browser: ff 
test date: 04.09.2017        

Actions:
1. register .mpdl user -> "Die Registrierung ist abgeschlossen. Bitte haben Sie etwas Geduld, bis Ihr Benutzerkonto von der Administration aktiviert ist.", but user gets activation e-mail right away and does not need the activation by admin ->user enters system via activation e-mail -> and a library is preinstalled

2.  register .mpdl user who earlier had an qa-keeper account-> same process as 1.) -> but no library is preinstalled

3. register user of external domain -> user gets system info "please wait for activation by admin" -> admin activates -> user gets info e-mail -> "anmelden" -> user enters system via e-mail and library preinstalled

4. register invalid mpdl-adress -> "Die Registrierung ist abgeschlossen. Bitte haben Sie etwas Geduld, bis Ihr Benutzerkonto von der Administration aktiviert ist."-> log in admin -> user is "inactive"

Observation:
1.and 2.: a)message after first registration process misleading, user thinks, he has to wait for admin's action b) admin gets "activation needed" e-mail -> since new user can activate his acount himself, this message seems to be misleading

3. and 4. as expected.

**Comment by vmakarenko** [comment]
Misleading messaging has been fixed

**Comment by hofmannc** [comment]
Testserver: qa keeper
Browser: ff
test date: 06.09.2017   

Result: ok. Current info text: "An activation email has been sent. Please check your email and click on the link to activate your account."
But Admin still gets the "New account need activated"-e-mail.
