### ISSUE TITLE
CDC - Update Certificate when metadata is updated

### ISSUE THREAD

**Issue by kleinfe** [MPDL/KEEPER#30]

**Comment by vmakarenko** [comment]
Implemented, please test at qa

**Comment by vmakarenko** [comment]
Fixed, please test on qa

**Comment by kleinfe** [comment]
Certificate is not renewed when Author or Description change, only when titel changes.

**Comment by vmakarenko** [comment]
The fields will be updated, the problem is ain imput of unicode symbols

**Comment by vmakarenko** [comment]
Implemented with Latin-1 + Latin-1 Supllement Gliphs

**Comment by kleinfe** [comment]
We still have an issue when description is updated and the text contains "".
The certificate is not updated

**Comment by vmakarenko** [comment]
fixed for "\`$ symbols - correct escaping for subrocess call with arguments

**Comment by kleinfe** [comment]
checked
